// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4KL-1QN1kREuxsnm7AztTNVnHrPdHnnQ',
    appId: '1:71024245686:web:94de10744cebe54b5e9f17',
    messagingSenderId: '71024245686',
    projectId: 'twitterclone-6306f',
    authDomain: 'twitterclone-6306f.firebaseapp.com',
    storageBucket: 'twitterclone-6306f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0j6hZNHvAyAnxbRG9gfe-aQAb39OzeQE',
    appId: '1:71024245686:android:7ac973398e6408a55e9f17',
    messagingSenderId: '71024245686',
    projectId: 'twitterclone-6306f',
    storageBucket: 'twitterclone-6306f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUuyagtfhf7T0QppZN7C8zBX098G-TGU',
    appId: '1:71024245686:ios:fa6dfcc1ee60a9805e9f17',
    messagingSenderId: '71024245686',
    projectId: 'twitterclone-6306f',
    storageBucket: 'twitterclone-6306f.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfUuyagtfhf7T0QppZN7C8zBX098G-TGU',
    appId: '1:71024245686:ios:fa6dfcc1ee60a9805e9f17',
    messagingSenderId: '71024245686',
    projectId: 'twitterclone-6306f',
    storageBucket: 'twitterclone-6306f.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4KL-1QN1kREuxsnm7AztTNVnHrPdHnnQ',
    appId: '1:71024245686:web:3dec4d6067b9aecf5e9f17',
    messagingSenderId: '71024245686',
    projectId: 'twitterclone-6306f',
    authDomain: 'twitterclone-6306f.firebaseapp.com',
    storageBucket: 'twitterclone-6306f.appspot.com',
  );
}
